version: "3"
services:
  node_new:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_new
    image: isvaku/notion-rss
    restart: unless-stopped
    environment:
      TZ: America/Mexico_City
      NOTION_API_KEY: "your_notion_api_key"
      NOTION_DATABASE_ID: "your_notion_database_id"
      RSS_FEED_URL: "your_rss_feed_url"
      MONGO_HOST: ""
      MONGO_PORT: "27017"
      MONGO_USER: ""
      MONGO_PASS: ""
      MONGO_DB_NAME: ""
    volumes:
      - nodeappdatanew:/usr/app

volumes:
  nodeappdatanew:
    driver: local
