version: "3"
services:
  nrss:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nrss
    image: isvaku/notion-rss:v1.0.1
    restart: unless-stopped
    environment:
      TZ: America/Mexico_City
      NOTION_API_KEY: "your_notion_api_key"
      NOTION_DATABASE_ID: "your_notion_database_id"
      RSS_FEED_URL: "your_rss_feed_url"
      MONGO_HOST: ""
      MONGO_PORT: "27017"
      MONGO_USER: ""
      MONGO_PASS: ""
      MONGO_DB_NAME: ""
      GET_ENTRIES_CRON: "0 * * * * "
      CREATE_NOTION_PAGES_CRON: "*/10 * * * *"
    volumes:
      - nrss_appdata:/usr/app

volumes:
  nrss_appdata:
    driver: local
