export const ATTRS_REGEX: RegExp = /\w+=\"[^"]*\"(?:\.?\"[^)]*\")*/g;
export const URL_REGEX: RegExp =
  /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&\/\/=]*)/g;
export const BANNED_ELEMENTS: readonly string[] = Object.freeze([
  "applet",
  "base",
  "basefont",
  "bgsound",
  "blink",
  "body",
  "button",
  "dir",
  "embed",
  "fieldset",
  "form",
  "frame",
  "frameset",
  "head",
  "html",
  "iframe",
  "ilayer",
  "input",
  "isindex",
  "label",
  "layer,",
  "legend",
  "link",
  "marquee",
  "menu",
  "meta",
  "noframes",
  "noscript",
  "object",
  "optgroup",
  "option",
  "param",
  "plaintext",
  "script",
  "select",
  "style",
  "textarea",
  "xml",
]);

export const BANNED_ATTRIBUTES: readonly string[] = Object.freeze([
  "lang",
  "language",
  "onmouseover",
  "onmouseout",
  "script",
  "font",
  "dir",
  "face",
  "size",
  "color",
  "class",
  "hspace",
  "border",
  "valign",
  "align",
  "background",
  "bgcolor",
  "text",
  "link",
  "vlink",
  "alink",
  "cellpadding",
  "cellspacing",
  "alt",
  "src",
  "srcset",
]);

export const RESOURCE_TYPES_ALLOWED: readonly string[] = Object.freeze([
  "image/gif",
  "image/jpeg",
  "image/png",
  "audio/wav",
  "audio/mpeg",
  "audio/amr",
  "application/pdf",
]);

export const MAX_BODY_LENGTH = 100;
